services:
  nhathuoc.webapi:
    image: lolmobi495/doan:nhathuoc
    build:
      context: .
      dockerfile: src/NhaThuoc.WebApi/Dockerfile
  
  # nhathuoc.gateway:
  #   image: lolmobi495/doan:nhathuoc-gateway
  #   build:
  #     context: .
  #     dockerfile: Gateway/Nhathuoc.Gateway/Dockerfile
